config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :gyms
  root 'gyms#index'
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :gyms
end

app/models/gym.rb
class Gym < ActiveRecord::Base
  belongs_to :city
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
	before_action :find_gym, only: [:show, :edit, :update, :destroy]

	def index
		if params[:city].blank?
			@gyms = Gym.all.order("created_at DESC")
		else
			@city_id = City.find_by(name: params[:city]).id
			@gyms = Gym.where(city_id: @city_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@gym = Gym.new
	end

	def create
		@gym = Gym.new(gyms_params)

		if @gym.save
			redirect_to @gym
		else
			render "New"
		end
	end

	def edit
	end

	def update
		if @gym.update(gyms_params)
			redirect_to @gym
		else
			render "Edit"
		end
	end

	def destroy
		@gym.destroy
		redirect_to root_path
	end

	private

	def gyms_params
		params.require(:gym).permit(:name, :latitude, :longitude, :address, :city_id)
	end

	def find_gym
		@gym = Gym.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<%= simple_form_for(@gym, html: { class: 'form-horizontal'}) do |f| %>
  <%= f.collection_select :city_id, City.all, :id, :name, {prompt: "Choose a city" }, input_html: { class: "dropdown-toggle" } %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :latitude, label: "Latitude" %>
  <%= f.input :longitude, label: "Longitude" %>
  <%= f.input :address, label: "Address" %>
  <br/>
  <%= f.button :submit %>
<% end %>

app/views/gyms/edit.html.erb
<h1>Edit Gym</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/gyms/index.html.erb
<% @gyms.each do |gym| %>
  <%= link_to gym.name, gym %> <br>
  <%= gym.address %> <br><br>
<% end %>

app/views/gyms/new.html.erb
<h1>New Gym</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/gyms/show.html.erb
Gym Name: <%= @gym.name %> <br>
Latitude: <%= @gym.latitude %> <br>
Longitude: <%= @gym.longitude %> <br>
Address: <%= @gym.address %> <br>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_gym_path(@gym) %>
<%= link_to "Delete", gym_path(@gym), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BygDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
  <li>
    <%= link_to "All Gyms", root_path %>
  </li>
  <% City.all.each do |city| %>
    <li>
      <%= link_to city.name, gyms_path(city: city.name) %>
    </li>
  <% end %>
</ul>
<%= link_to "New Gym", new_gym_path %>
<br><br>

<%= yield %>

</body>
</html>